FROM nvcr.io/nvidia/tensorrt:25.09-py3

ENV DEBIAN_FRONTEND=noninteractive
RUN ln -s -f /bin/true /usr/bin/chfn
RUN echo "resolvconf resolvconf/linkify-resolvconf boolean false" | debconf-set-selections

RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    libcurl4-openssl-dev \
    wget \
    zlib1g-dev \
    git \
    pkg-config \
    python3 \
    python3-pip \
    python3-dev \
    python3-setuptools \
    python3-wheel \
    sudo \
    ssh \
    pbzip2 \
    pv \
    bzip2 \
    unzip \
    software-properties-common \
    build-essential libopenblas-dev \
    clang-20 lld-20 clangd-20 libomp-dev libboost-all-dev \
    tmux fish libjemalloc-dev libjemalloc2  && \
    ln -s /usr/lib/$(uname -m)-linux-gnu/libjemalloc.so.2 /usr/local/lib/libjemalloc.so && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip
RUN pip3 install --pre torch torchvision --index-url https://download.pytorch.org/whl/nightly/cu130
RUN pip3 install cython scipy mup cshogi onnx

WORKDIR /tmp
RUN git clone https://github.com/jj1guj/DeepLearningShogi && \
    cd DeepLearningShogi && \
    git checkout wcsc35 && \
    pip install -v . && \
    rm -r ~/.cache/pip && \
    rm -rf /tmp/DeepLearningShogi

WORKDIR /root
ENV LD_PRELOAD=/usr/local/lib/libjemalloc.so
